branch-defaults:
  frontend:
    environment: null
    group_suffix: null
global:
  application_name: Indonesiaku
  default_ec2_keyname: aws-eb
  default_platform: Ruby 2.2 (Puma)
  default_region: us-west-2
  profile: eb-cli
  sc: git
